application: hjfreyer-com
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /.*pentris.*
  script: redirect.py
